export const ensDiamondsAbi = [
  {
    type: "constructor",
    inputs: [
      {
        name: "controller_",
        type: "address",
        internalType: "contract IENSDiamondsRegistrarController",
      },
      { name: "baseRegistrar_", type: "address", internalType: "contract IBaseRegistrar" },
      { name: "safeSingleton_", type: "address", internalType: "contract ISafe" },
      { name: "safeProxyFactory_", type: "address", internalType: "contract SafeProxyFactory" },
      { name: "safeFallbackHandler_", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  { type: "fallback", stateMutability: "payable" },
  { type: "receive", stateMutability: "payable" },
  {
    type: "function",
    name: "BASE_REGISTRAR",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IBaseRegistrar" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "CONTROLLER",
    inputs: [],
    outputs: [
      { name: "", type: "address", internalType: "contract IENSDiamondsRegistrarController" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_MEMBERS",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MIN_MEMBERS",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "SAFE_FALLBACK_HANDLER",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "SAFE_PROXY_FACTORY",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract SafeProxyFactory" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "SAFE_PROXY_INIT_CODE_HASH",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "SAFE_SINGLETON",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract ISafe" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "TARGET_INTENT_TYPEHASH",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "balanceOf",
    inputs: [
      { name: "vaultId", type: "bytes32", internalType: "bytes32" },
      { name: "member", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "balance", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "beginAcquisition",
    inputs: [{ name: "vaultId", type: "bytes32", internalType: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancel",
    inputs: [{ name: "vaultId", type: "bytes32", internalType: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claim",
    inputs: [
      { name: "vaultId", type: "bytes32", internalType: "bytes32" },
      { name: "recipient", type: "address", internalType: "address payable" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createVault",
    inputs: [
      { name: "vaultSalt", type: "bytes32", internalType: "bytes32" },
      { name: "maxSpend", type: "uint96", internalType: "uint96" },
      { name: "registrationDuration", type: "uint32", internalType: "uint32" },
      { name: "owners", type: "address[]", internalType: "address[]" },
      { name: "targetIntent", type: "bytes32", internalType: "bytes32" },
      { name: "ensCommitment", type: "bytes32", internalType: "bytes32" },
      { name: "vaultURI_", type: "string", internalType: "string" },
    ],
    outputs: [{ name: "vaultId", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "deposit",
    inputs: [{ name: "vaultId", type: "bytes32", internalType: "bytes32" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "expireAcquisition",
    inputs: [{ name: "vaultId", type: "bytes32", internalType: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getOwners",
    inputs: [{ name: "vaultId", type: "bytes32", internalType: "bytes32" }],
    outputs: [{ name: "owners", type: "address[]", internalType: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "predictSafe",
    inputs: [
      { name: "creator", type: "address", internalType: "address" },
      { name: "vaultSalt", type: "bytes32", internalType: "bytes32" },
      { name: "owners", type: "address[]", internalType: "address[]" },
    ],
    outputs: [
      { name: "vaultId", type: "bytes32", internalType: "bytes32" },
      { name: "safe", type: "address", internalType: "address" },
      { name: "threshold", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "purchase",
    inputs: [
      { name: "vaultId", type: "bytes32", internalType: "bytes32" },
      { name: "normalizedLabel", type: "string", internalType: "string" },
      { name: "targetSalt", type: "bytes32", internalType: "bytes32" },
      { name: "ensSecret", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "totalLiabilities",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "vaultURI",
    inputs: [{ name: "vaultId", type: "bytes32", internalType: "bytes32" }],
    outputs: [{ name: "uri", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "vaults",
    inputs: [{ name: "vaultId", type: "bytes32", internalType: "bytes32" }],
    outputs: [
      { name: "creator", type: "address", internalType: "address" },
      { name: "escrowed", type: "uint96", internalType: "uint96" },
      { name: "maxSpend", type: "uint96", internalType: "uint96" },
      { name: "committedAt", type: "uint40", internalType: "uint40" },
      { name: "registrationDuration", type: "uint32", internalType: "uint32" },
      { name: "state", type: "uint8", internalType: "enum IENSDiamonds.State" },
      { name: "targetIntent", type: "bytes32", internalType: "bytes32" },
      { name: "ensCommitment", type: "bytes32", internalType: "bytes32" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "withdraw",
    inputs: [
      { name: "vaultId", type: "bytes32", internalType: "bytes32" },
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "recipient", type: "address", internalType: "address payable" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "AcquisitionCommitted",
    inputs: [
      { name: "vaultId", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "ensCommitment", type: "bytes32", indexed: false, internalType: "bytes32" },
      { name: "predictedSafe", type: "address", indexed: true, internalType: "address" },
      { name: "committedAt", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "threshold", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AcquisitionExpired",
    inputs: [{ name: "vaultId", type: "bytes32", indexed: true, internalType: "bytes32" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "Claimed",
    inputs: [
      { name: "vaultId", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "member", type: "address", indexed: true, internalType: "address" },
      { name: "recipient", type: "address", indexed: true, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Deposited",
    inputs: [
      { name: "vaultId", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "member", type: "address", indexed: true, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "NameAcquired",
    inputs: [
      { name: "vaultId", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "labelhash", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "safe", type: "address", indexed: true, internalType: "address" },
      { name: "protocolPrice", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "refundableBalance", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "VaultCancelled",
    inputs: [{ name: "vaultId", type: "bytes32", indexed: true, internalType: "bytes32" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "VaultCreated",
    inputs: [
      { name: "vaultId", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "creator", type: "address", indexed: true, internalType: "address" },
      { name: "maxSpend", type: "uint96", indexed: false, internalType: "uint96" },
      { name: "registrationDuration", type: "uint32", indexed: false, internalType: "uint32" },
      { name: "owners", type: "address[]", indexed: false, internalType: "address[]" },
      { name: "targetIntent", type: "bytes32", indexed: false, internalType: "bytes32" },
      { name: "ensCommitment", type: "bytes32", indexed: false, internalType: "bytes32" },
      { name: "vaultURI", type: "string", indexed: false, internalType: "string" },
      { name: "creatorDeposit", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Withdrawn",
    inputs: [
      { name: "vaultId", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "member", type: "address", indexed: true, internalType: "address" },
      { name: "recipient", type: "address", indexed: true, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  { type: "error", name: "CommitmentAtBoundary", inputs: [] },
  { type: "error", name: "CommitmentChanged", inputs: [] },
  {
    type: "error",
    name: "CommitmentExpired",
    inputs: [{ name: "expiredAt", type: "uint256", internalType: "uint256" }],
  },
  { type: "error", name: "CommitmentMismatch", inputs: [] },
  {
    type: "error",
    name: "CommitmentNotExpired",
    inputs: [{ name: "expiresAt", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "CommitmentTooYoung",
    inputs: [{ name: "validAt", type: "uint256", internalType: "uint256" }],
  },
  { type: "error", name: "DirectETHNotAccepted", inputs: [] },
  { type: "error", name: "ENSVerificationFailed", inputs: [] },
  { type: "error", name: "ETHTransferFailed", inputs: [] },
  { type: "error", name: "FundingLimitExceeded", inputs: [] },
  { type: "error", name: "InsufficientBalance", inputs: [] },
  {
    type: "error",
    name: "InsufficientFunding",
    inputs: [
      { name: "price", type: "uint256", internalType: "uint256" },
      { name: "escrowed", type: "uint256", internalType: "uint256" },
    ],
  },
  { type: "error", name: "InvalidAddress", inputs: [] },
  { type: "error", name: "InvalidAmount", inputs: [] },
  { type: "error", name: "InvalidConfiguration", inputs: [] },
  {
    type: "error",
    name: "InvalidContract",
    inputs: [{ name: "dependency", type: "address", internalType: "address" }],
  },
  { type: "error", name: "InvalidOwners", inputs: [] },
  {
    type: "error",
    name: "InvalidState",
    inputs: [{ name: "current", type: "uint8", internalType: "enum IENSDiamonds.State" }],
  },
  { type: "error", name: "NotMember", inputs: [] },
  { type: "error", name: "NothingToClaim", inputs: [] },
  { type: "error", name: "Reentrancy", inputs: [] },
  { type: "error", name: "SafeVerificationFailed", inputs: [] },
  { type: "error", name: "TargetMismatch", inputs: [] },
  { type: "error", name: "Unauthorized", inputs: [] },
  { type: "error", name: "VaultAlreadyExists", inputs: [] },
  { type: "error", name: "VaultNotFound", inputs: [] },
] as const;
