[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc_version = "0.8.36"
auto_detect_solc = false
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = false
deny = "warnings"
ignored_warnings_from = ["lib"]
no_match_coverage = "^(test|script)/"

[fuzz]
runs = 1000

[invariant]
runs = 256
depth = 64
fail_on_revert = false
show_metrics = true

[profile.gas]
gas_reports = ["*"]

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = false
multiline_func_header = "attributes_first"
sort_imports = true

[lint]
severity = ["high", "med", "low", "info", "gas", "code-size"]
ignore = ["lib/**/*"]

[rpc_endpoints]
mainnet = "${ETHEREUM_MAINNET_RPC_URL}"
sepolia = "${ETHEREUM_SEPOLIA_RPC_URL}"


[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
